#!/bin/sh

#!/bin/sh

start() {

    
    echo "started"
    cd /root/peregrine-integrator
    
    ./bin/integrator --daemon conf/peregrine-coverage.py > /var/log/peregrine-coverage.log &
    ./bin/integrator --daemon conf/peregrine-dox.py > /var/log/peregrine-dox.log &
    ./bin/integrator --daemon conf/peregrine-test.py > /var/log/peregrine-test.log &
    ./bin/integrator --daemon conf/peregrine-integration.py > /var/log/peregrine-integration.log &

}

stop() {

    pkill -f 'integrator --daemon'

    echo "stopped"

}

args=$@
shift $(expr $# - 1)
command=$1

case $command in

    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "ERROR: unknown command: $command" 
        exit 1
        ;;

esac
